nama=input("Nama\t\t\t:")
Nim=input("NIM\t\t\t:")
Paralel=input("Kelas Paralel\t\t:")
Tempat=input("Tempat/tanggal Lahir\t:")
Alamat=input("Alamat\t\t\t:")
Hobby=input("Hobby\t\t\t:")
No=input("No. HP\t\t\t:")
print("\n")
print("Nama\t\t\t:"+ nama)
print("NIM\t\t\t:"+ Nim)
print("Kelas Paralel\t\t:"+Paralel)
print("Tempat/tanggal Lahir\t:"+Tempat)
print("Alamat\t\t\t:"+Alamat)
print("Hobby\t\t\t:"+Hobby)
print("No. HP\t\t\t:"+No)