print ("#########################")
print ("#                       #")
print ("#  Harry Pratama Yunus  #")
print ("#     2310817210010     #")
print ("#                       #")
print ("#########################")